CREATE TABLE `brokerProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`brokerName` text,
	`brokerTitle` text,
	`brokerPhone` varchar(32),
	`brokerCompany` text,
	`brokerLogoUrl` text,
	`brokerPhotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `brokerProfiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `brokerProfiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`propertyName` text NOT NULL,
	`propertyAddress` text,
	`city` varchar(100),
	`state` varchar(50),
	`market` varchar(100),
	`totalSqFt` int,
	`floorNumber` varchar(20),
	`floorPlanUrl` text,
	`floorPlanKey` text,
	`inputMethod` enum('upload','scan') DEFAULT 'upload',
	`status` enum('draft','analyzing','complete','error') NOT NULL DEFAULT 'draft',
	`tenantName` text,
	`headcount` int,
	`industry` varchar(100),
	`programNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scenarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`scenarioNumber` int NOT NULL,
	`label` varchar(100),
	`efficiencyScore` int,
	`usableSqFt` int,
	`totalSqFt` int,
	`roomBreakdown` json,
	`layoutDescription` text,
	`layoutSvg` text,
	`budgetLow` float,
	`budgetMid` float,
	`budgetHigh` float,
	`costPerSqFtLow` float,
	`costPerSqFtMid` float,
	`costPerSqFtHigh` float,
	`budgetBreakdown` json,
	`scheduleWeeksLow` int,
	`scheduleWeeksMid` int,
	`scheduleWeeksHigh` int,
	`schedulePhases` json,
	`aiSummary` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `scenarios_id` PRIMARY KEY(`id`)
);
